@host=http://localhost:5059
POST {{host}}/asset/add
Content-Type: application/json

{
    "money" : {
        "amount" : "20.0",
        "CurrencyType": 1
    },
     "description" : "Engin Santader Dollar"
}